# Generated by Django 5.2 on 2025-05-21 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaproducto',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_tiendas', to='myapp.producto'),
        ),
        migrations.AlterField(
            model_name='tiendaproducto',
            name='tienda_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_precios', to='myapp.tienda'),
        ),
    ]
